all::
	g++ -g -Wno-write-strings  -o bscore data.cc main.cc model.cc options.cc subset.cc utils.cc variable.cc  binSearchObj.cc Tau.cc LgBetaTable.cc IncreasingFunctOnInterval.cc pwl_interp_2d.cc  -I.\
		-lpthread -lm -ldl -lutil -lm -lstdc++


Debug::
	g++ -g -Wno-write-strings  -o bin/Debug/SparsityBoost data.cc model.cc options.cc subset.cc utils.cc variable.cc  binSearchObj.cc Tau.cc LgBetaTable.cc IncreasingFunctOnInterval.cc pwl_interp_2d.cc  -I.\
		-lpthread -lm -ldl -lutil -lm -lstdc++
